<a href="https://colab.research.google.com/github/Namrata-cse/Feature_selection_methods/blob/main/FS_Fischerscore(supervised).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
!pip install skfeature-chappers

     |████████████████████████████████| 66 kB 4.1 MB/s 


In [38]:
#libraries
import numpy as np
import scipy.io
from sklearn.model_selection import train_test_split
from skfeature.function.similarity_based import fisher_score
from sklearn import svm
from sklearn.metrics import accuracy_score


In [3]:
mat = scipy.io.loadmat("COIL20.mat")

In [4]:
X=mat['X']
print(X)

[[0.01568627 0.01568627 0.01568627 ... 0.01568627 0.01568627 0.01568627]
 [0.01960784 0.01960784 0.01960784 ... 0.01960784 0.01960784 0.01960784]
 [0.01568627 0.01568627 0.01568627 ... 0.01568627 0.01568627 0.01568627]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [5]:
y = mat['Y'][:, 0] 

In [7]:
print(y)

[ 1  1  1 ... 20 20 20]


In [8]:
n_samples, n_features = np.shape(X)

In [9]:
print (n_samples, n_features)

1440 1024


In [10]:
n_labels = np.shape(y)

In [11]:
print(n_labels)

(1440,)


In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40)

In [16]:
print( X_train)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.02352941 0.02352941 0.02352941 ... 0.02352941 0.02352941 0.02352941]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.01568627 0.01568627 0.01568627 ... 0.01568627 0.01568627 0.01568627]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [17]:
print(y_train)

[17  2 12 ...  1  4 19]


In [18]:
print(X_test)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.01568627 0.01568627 0.01568627 ... 0.01568627 0.01568627 0.01568627]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [19]:
print(y_test)

[ 8 15  1 10 11 20 18  5 17 17 16 20 12  6 15 19 20 11 11  6 11 11 16 11
 18  9  6 17  4  9  2 17 16 13 20  6 20 13 15  2  4  7 20 20  1  9  2  2
  8  7  5 16  2 13 10 15 18 14 14 20 11 17  8  6 12  1  3 15  1 14 10  4
 13 13 13  4  2 12 17  3  3  3 15 18 14  6  6 11 12  1  2 11 20 17  9 11
  2 12  2  7  3  5  8  1  1 14  5 18 15  4  7  8  2  3 12 13  7  6  2  4
 14  3 16 12  1 18  6 12  9  2 17  9  9 16 11  2  1 14 11 14 17  7 13 19
 18  9 16  4  8  4 18  4  1 17 13  6 12 11  3 11  6 13  1 20 14 11 19  4
 10 17 20 19  3 16 19  7  4  4 17 18 15 11  9 18 11  6 12 15  5 15 17 17
 11 14  7  9  9  6 18 15  4  4 20  3 10 10  2  6  6 13 14  4  4  4  5 15
 17  8  1 18 10 20 17 13  9 15 17 15  5 19  5 14 19  4  9 16 14 13 13  9
 15 15 16  7 15 12 19 14  9  3  5  8  2 12  7 17  2 10 10 16  3  2 13 10
 17 11  2 18 19 15 20 10 17  8  1  4 15  7 16  6  7 15  7 18 13 15 17  7]


In [24]:
#Fischer score
#We take Fisher Score algorithm as an example to explain how to perform feature selection on the training set.
# First, we compute the fisher scores of all features using the training set.
score = fisher_score.fisher_score(X_train, y_train)
print (score)

[  0   1 992 ... 989 926 126]


In [26]:
print(score.size)

1024


In [27]:
#Rank features in an descending order according to fisher scores and outputs the ranking index:
idx = fisher_score.fisher_score(X_train, y_train, mode='rank') 

In [28]:
print(idx)

[  0   1 992 ... 989 926 126]


In [29]:
num_fea = 5

In [31]:
selected_features_train = X_train[:, idx[0:num_fea]]
selected_features_test = X_test[:, idx[0:num_fea]]
print (selected_features_train)

[[0.         0.         0.         0.         0.        ]
 [0.02352941 0.02352941 0.02352941 0.02352941 0.02352941]
 [0.         0.         0.         0.         0.        ]
 ...
 [0.01568627 0.01568627 0.01568627 0.01568627 0.01568627]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]]


In [32]:
print (selected_features_train.shape)

(1152, 5)


In [33]:
print (selected_features_test)

[[0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.01568627 0.01568627 0.01568627 0.01568627 0.01568627]
 ...
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]]


In [35]:
clf = svm.LinearSVC()


In [36]:
clf.fit(selected_features_train, y_train)

LinearSVC()

In [37]:
y_predict = clf.predict(selected_features_test)
print (y_predict)

[8 8 2 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 2 8 8 8 8 8 8
 8 8 2 8 8 8 8 2 8 2 2 8 8 8 8 2 8 8 8 8 8 8 8 8 8 8 8 8 2 8 8 2 8 8 8 8 8
 8 8 2 8 8 8 8 8 8 8 8 8 8 8 8 2 2 8 8 8 8 8 2 8 2 8 8 8 8 2 2 8 8 8 8 8 8
 8 2 8 8 8 8 8 2 8 8 8 8 8 2 8 8 8 8 2 8 8 8 8 8 2 2 8 8 8 8 8 8 8 8 8 8 8
 8 8 8 8 2 8 8 8 8 8 8 8 8 8 2 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8
 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 2 8 8 8 8 8 8 8 8 8 8 8 2 8 8 8
 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 2 8 8 8 2 8 8
 8 8 2 8 8 8 8 2 8 8 8 8 8 8 8 2 8 8 8 8 8 8 8 8 8 8 8 8 8]


In [39]:
acc = accuracy_score(y_test, y_predict)

In [40]:
print (acc)

0.09375
